[package]
name = "guglefs-app"
version.workspace = true
edition.workspace = true
license.workspace = true
rust-version.workspace = true

[lib]
name = "guglefs_app_lib"
crate-type = ["staticlib", "cdylib", "rlib"]

[build-dependencies]
tauri-build = { version = "2", features = [] }

[target.'cfg(windows)'.build-dependencies]
winfsp_build = "0.1.1"

[dependencies]
guglefs-core = { path = "../crates/guglefs-core" }
guglefs-mount = { path = "../crates/guglefs-mount" }
guglefs-remote = { path = "../crates/guglefs-remote" }
serde.workspace = true
serde_json.workspace = true
tauri = { version = "2", features = ["tray-icon"] }
tauri-plugin-dialog = "2"
tauri-plugin-single-instance = "2"
tokio.workspace = true
totp-rs = { version = "5.7.2", features = ["gen_secret", "otpauth", "qr", "zeroize"] }

[target.'cfg(windows)'.dependencies]
keyring = { version = "3.6.3", features = ["windows-native"] }
