[package]
name = "guglefs-mount"
version.workspace = true
edition.workspace = true
license.workspace = true
rust-version.workspace = true

[features]
default = ["remote-backends"]
remote-backends = ["dep:guglefs-remote"]

[dependencies]
async-trait.workspace = true
guglefs-core = { path = "../guglefs-core" }

[target.'cfg(unix)'.dependencies]
fuser = "0.18"
libc = "0.2"
tokio = { workspace = true, features = ["rt"] }

[target.'cfg(windows)'.dependencies]
tokio = { workspace = true, features = ["rt"] }
widestring = "1"
winfsp_wrs = "0.4.1"

[target.'cfg(any(unix, windows))'.dependencies]
guglefs-remote = { path = "../guglefs-remote", optional = true }
