[package]
name = "guglefs-mount"
version.workspace = true
edition.workspace = true
license.workspace = true
rust-version.workspace = true

[dependencies]
async-trait.workspace = true
guglefs-core = { path = "../guglefs-core" }

[target.'cfg(windows)'.dependencies]
guglefs-remote = { path = "../guglefs-remote" }
tokio.workspace = true
widestring = "1"
winfsp_wrs = "0.4.1"

