services:
  ftp:
    image: stilliard/pure-ftpd:hardened
    command:
      - /run.sh
      - -l
      - puredb:/etc/pure-ftpd/pureftpd.pdb
      - -E
      - -j
      - -R
      - -P
      - 127.0.0.1
      - -s
      - -A
      - -Z
      - -H
      - "-4"
      - -X
      - -x
    environment:
      PUBLICHOST: "127.0.0.1"
      FTP_USER_NAME: "guglefs"
      FTP_USER_PASS: "guglefs-test"
      FTP_USER_HOME: "/home/guglefs"
      FTP_PASSIVE_PORTS: "21000:21010"
    ports:
      - "2121:21"
      - "21000-21010:21000-21010"
  sftp:
    image: atmoz/sftp:alpine
    command: "guglefs:guglefs-test:1001::upload"
    ports:
      - "2222:22"
